statement ::= if | while | assign
assign ::= def | defshort
def ::= VAR STRING(*) EQ assignval
defshort ::= STRING(*) DEFEQ assignval
assignval ::= binop | func
binop ::= value | value OP value
value ::= INT(*)
OP ::= PLUS | MINUS | MULT | DIV | AND | OR | GE | LE | GEQ | LEQ | NEQ
func ::= LPAREN args RPAREN IMPL fbody
args ::= (STRING(*))*...............TODO
fbody ::= binop | if | while | block